import path from 'node:path';

const NAVY = 'FF18223A';
const PURPLE = 'FF5747C7';
const BORDER = 'FFD7DCE5';
const SOFT = 'FFF5F6F9';

export function spreadsheetSafeCell(value) {
  if (value == null) return '';
  if (typeof value !== 'string') return value;
  return /^[\s\u0000-\u001f]*[=+\-@]/u.test(value) ? `'${value}` : value;
}

function humanize(value) {
  return String(value || '').replace(/[-_]+/g, ' ').replace(/\b\w/g, (character) => character.toUpperCase());
}

function addTableSheet(workbook, name, columns, rows) {
  const sheet = workbook.addWorksheet(name, { views: [{ state: 'frozen', ySplit: 1, showGridLines: false }] });
  sheet.columns = columns.map(([header, width]) => ({ header, width }));
  const header = sheet.getRow(1);
  header.height = 30;
  header.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 10 };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
    cell.alignment = { vertical: 'middle', horizontal: 'left', wrapText: true };
  });
  for (const values of rows) {
    const row = sheet.addRow(values.map(spreadsheetSafeCell));
    row.alignment = { vertical: 'top', wrapText: true };
    row.eachCell((cell) => { cell.border = { bottom: { style: 'thin', color: { argb: BORDER } } }; });
  }
  if (columns.length) sheet.autoFilter = { from: 'A1', to: sheet.getRow(1).getCell(columns.length).address };
  sheet.pageSetup = { orientation: columns.length > 6 ? 'landscape' : 'portrait', fitToPage: true, fitToWidth: 1, fitToHeight: 0 };
  return sheet;
}

function addSummary(workbook, title, facts) {
  const sheet = workbook.addWorksheet('Summary', { views: [{ showGridLines: false }] });
  sheet.columns = [{ width: 28 }, { width: 68 }];
  sheet.mergeCells('A1:B2');
  const heading = sheet.getCell('A1');
  heading.value = title;
  heading.font = { size: 20, bold: true, color: { argb: 'FFFFFFFF' } };
  heading.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
  heading.alignment = { vertical: 'middle' };
  let rowIndex = 4;
  for (const [label, value] of facts) {
    const row = sheet.getRow(rowIndex++);
    row.values = [label, spreadsheetSafeCell(value)];
    row.getCell(1).font = { bold: true, color: { argb: PURPLE } };
    row.getCell(2).alignment = { wrapText: true };
    row.eachCell((cell) => { cell.border = { bottom: { style: 'thin', color: { argb: BORDER } } }; });
  }
  sheet.getRow(rowIndex + 1).getCell(1).value = 'Generated by Web Engineering Toolkit';
  sheet.getRow(rowIndex + 1).getCell(1).font = { italic: true, color: { argb: 'FF5F6879' } };
  return sheet;
}

function lighthouseSheets(workbook, summary) {
  const overview = summary.overview || {};
  addSummary(workbook, 'Lighthouse Technical Report', [['Project', overview.projectName], ['Base URL', overview.baseUrl], ['Generated', summary.generatedAt], ['Mode', humanize(overview.mode)], ['Devices', (overview.devices || []).join(', ')], ['Categories', (overview.categories || []).map(humanize).join(', ')], ['Pages analyzed', overview.pages], ['Valid runs', overview.validAudits], ['Failed runs', overview.failedAudits], ['Important findings', overview.totalFindings || 0]]);
  addTableSheet(workbook, 'Page Results', [['Page', 45], ['Device', 14], ['Status', 15], ['Performance', 14], ['Accessibility', 14], ['Best Practices', 15], ['SEO', 12], ['LCP ms', 13], ['Findings', 12]], (summary.rows || []).map((row) => [row.path, humanize(row.device), humanize(row.status), row.performance, row.accessibility, row.bestPractices, row.seo, row.lcpMs, row.findingCount || 0]));
  const findings = (summary.insights?.categories || []).flatMap((category) => (category.groups || []).flatMap((group) => (group.findings || []).map((finding) => [category.title, group.title, finding.title, humanize(finding.status), finding.affected?.length || finding.occurrences || 0, finding.displayValue || finding.explanation || finding.description || ''])));
  addTableSheet(workbook, 'Findings', [['Category', 22], ['Group', 28], ['Finding', 44], ['Status', 16], ['Affected', 12], ['Details', 72]], findings);
}

function assetSheets(workbook, result) {
  addSummary(workbook, 'Asset & Page-Weight Analysis', [['Project', result.projectName], ['Base URL', result.baseUrl], ['Generated', result.generatedAt], ['Browser', result.browser?.name], ['Device', humanize(result.device)], ['Pages analyzed', result.summary?.pageCount], ['Average bytes', Math.round(result.summary?.averageBytes || 0)], ['Average requests', Math.round(result.summary?.averageRequests || 0)], ['Third-party bytes', result.summary?.thirdPartyBytes || 0]]);
  addTableSheet(workbook, 'Page Results', [['Page', 54], ['Status', 12], ['Transfer bytes', 16], ['Requests', 12], ['JavaScript bytes', 18], ['Image bytes', 16], ['Third-party bytes', 18], ['Findings', 12]], (result.pages || []).map((page) => [page.finalUrl, page.status, page.totalTransferBytes, page.requestCount, page.breakdown?.script || 0, page.breakdown?.image || 0, page.thirdPartyBytes || 0, page.findings?.length || 0]));
  addTableSheet(workbook, 'Assets', [['Source page', 48], ['Asset URL', 78], ['Type', 15], ['Transfer bytes', 18], ['Host', 32], ['HTTP status', 14], ['Cache-Control', 32]], (result.pages || []).flatMap((page) => (page.resources || []).map((asset) => [page.finalUrl, asset.url, humanize(asset.category), asset.transferBytes, asset.host, asset.status, asset.cacheControl || 'Not set'])));
  addTableSheet(workbook, 'Findings', [['Priority', 14], ['Finding', 42], ['Detail', 68], ['Recommendation', 68], ['Pages', 58]], (result.findings || []).map((finding) => [humanize(finding.severity), finding.title, finding.detail, finding.recommendation, (finding.pages || []).join('\n')]));
}

function brokenLinksSheets(workbook, result) {
  addSummary(workbook, 'Broken Links & Resources Report', [['Project', result.projectName], ['Base URL', result.baseUrl], ['Generated', result.generatedAt], ['Scan scope', humanize(result.scope?.mode)], ['Pages scanned', result.summary?.pagesScanned], ['Targets checked', result.summary?.uniqueTargets], ['Needs attention', result.summary?.broken || 0], ['Redirected', result.summary?.redirected || 0], ['Healthy', result.summary?.healthy || 0]]);
  addTableSheet(workbook, 'Target Inventory', [['Outcome', 18], ['HTTP status', 14], ['Target URL', 75], ['Final URL', 75], ['Types', 24], ['Internal', 12], ['Occurrences', 14], ['Source pages', 68], ['Check method', 20], ['Reason', 52]], (result.targets || []).map((target) => [humanize(target.outcome), target.httpStatus || '', target.targetUrl, target.finalUrl || '', (target.referenceTypes || []).map(humanize).join(', '), target.internal ? 'Yes' : 'No', target.occurrenceCount || 0, (target.sourcePages || []).join('\n'), humanize(target.checkMethod), target.failureReason || '']));
}

function complianceSheets(workbook, summary) {
  addSummary(workbook, 'Technical Compliance Pre-Assessment', [['Project', summary.projectName], ['Target URL', summary.finalUrl || summary.requestedUrl], ['Generated', summary.generatedAt], ['Assessment type', summary.assessmentType], ['Evidence level', summary.evidenceLevel], ['Compliance conclusion', summary.complianceConclusion], ['Coverage', summary.coverage], ['Mapping catalog', summary.mappingCatalogVersion], ['Schema version', summary.schemaVersion], ['Workflow revision', summary.workflow?.revision || 0]]);
  addTableSheet(workbook, 'Findings', [['Finding ID', 36], ['Title', 48], ['Severity', 14], ['Status', 20], ['Affected URL', 62], ['Observation', 72], ['Recommendation', 72], ['Review decision', 24], ['Review note', 60]], (summary.findings || []).map((finding) => [finding.id, finding.title, humanize(finding.severity), humanize(finding.findingStatus || finding.status), finding.affectedUrl || '', finding.description || finding.impact || '', finding.recommendation || '', finding.decision?.reviewDecision || '', finding.decision?.reason || '']));
  addTableSheet(workbook, 'Control Evidence', [['Control ID', 36], ['Evidence state', 34], ['Control satisfaction', 24], ['Coverage', 16], ['Source checks', 62], ['Mappings', 68], ['Manual review', 20], ['Limitations', 72]], (summary.controlEvaluations || []).map((control) => [control.controlId, humanize(control.state), humanize(control.controlSatisfaction || 'not_determined'), humanize(control.coverage || 'partial'), (control.provenanceSummary?.sourceCheckIds || []).join('\n'), (control.mappings || []).map((mapping) => `${mapping.mappingId || ''}: ${mapping.relationship || ''}`).join('\n'), control.manualReviewRequired === false ? 'No' : 'Yes', (control.limitations || []).join('\n')]));
}

export async function writeReportXlsx({ root, reportType, data }) {
  const { default: ExcelJS } = await import('exceljs');
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Web Engineering Toolkit';
  workbook.lastModifiedBy = 'Web Engineering Toolkit';
  workbook.subject = 'Web Engineering Toolkit technical report export';
  workbook.created = new Date(data.generatedAt || Date.now());
  workbook.modified = new Date(data.generatedAt || Date.now());
  if (reportType === 'lighthouse') lighthouseSheets(workbook, data);
  else if (reportType === 'asset-page-weight') assetSheets(workbook, data);
  else if (reportType === 'broken-links-resources') brokenLinksSheets(workbook, data);
  else if (reportType === 'security-compliance') complianceSheets(workbook, data);
  else throw new Error(`Unsupported XLSX report type: ${reportType}`);
  for (const sheet of workbook.worksheets) sheet.eachRow((row, rowNumber) => { if (rowNumber > 1 && rowNumber % 2 === 0) row.eachCell((cell) => { if (!cell.fill?.type) cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SOFT } }; }); });
  await workbook.xlsx.writeFile(path.join(root, 'summary.xlsx'));
}
